// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrintersSystem.Models;

namespace PrintersSystem.Migrations
{
    [DbContext(typeof(PrintersSystemContext))]
    partial class PrintersSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PrinterManagement.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Recepcion"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sala de juntas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gerencia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Facturacion"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Contabilidad"
                        });
                });

            modelBuilder.Entity("PrinterManagement.Models.Maintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("LocationId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("PrinterId");

                    b.Property<string>("Technician")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("PrinterId");

                    b.ToTable("Maintenance");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2019, 5, 13, 14, 39, 52, 594, DateTimeKind.Local).AddTicks(1921),
                            LocationId = 1,
                            Name = "Cambio Tinta1",
                            PrinterId = 1,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2019, 5, 29, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(2947),
                            LocationId = 1,
                            Name = "Limpieza2",
                            PrinterId = 1,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2019, 5, 31, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3014),
                            LocationId = 1,
                            Name = "Calibracion3",
                            PrinterId = 1,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2019, 5, 13, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3055),
                            LocationId = 1,
                            Name = "Cambio Tinta4",
                            PrinterId = 2,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2019, 5, 30, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3090),
                            LocationId = 1,
                            Name = "Limpieza5",
                            PrinterId = 2,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2019, 5, 29, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3128),
                            LocationId = 1,
                            Name = "Calibracion6",
                            PrinterId = 2,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2019, 5, 31, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3162),
                            LocationId = 1,
                            Name = "Cambio Tinta7",
                            PrinterId = 3,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2019, 5, 24, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3194),
                            LocationId = 1,
                            Name = "Limpieza8",
                            PrinterId = 3,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2019, 6, 1, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3227),
                            LocationId = 1,
                            Name = "Calibracion9",
                            PrinterId = 3,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2019, 5, 16, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3264),
                            LocationId = 1,
                            Name = "Cambio Tinta10",
                            PrinterId = 4,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2019, 5, 26, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3296),
                            LocationId = 1,
                            Name = "Limpieza11",
                            PrinterId = 4,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2019, 5, 30, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3327),
                            LocationId = 1,
                            Name = "Calibracion12",
                            PrinterId = 4,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2019, 5, 17, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3360),
                            LocationId = 1,
                            Name = "Cambio Tinta13",
                            PrinterId = 5,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2019, 5, 15, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3391),
                            LocationId = 1,
                            Name = "Limpieza14",
                            PrinterId = 5,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2019, 5, 24, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3422),
                            LocationId = 1,
                            Name = "Calibracion15",
                            PrinterId = 5,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2019, 5, 31, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3452),
                            LocationId = 2,
                            Name = "Cambio Tinta16",
                            PrinterId = 6,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2019, 6, 1, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3484),
                            LocationId = 2,
                            Name = "Limpieza17",
                            PrinterId = 6,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2019, 5, 19, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3649),
                            LocationId = 2,
                            Name = "Calibracion18",
                            PrinterId = 6,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2019, 5, 14, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3684),
                            LocationId = 2,
                            Name = "Cambio Tinta19",
                            PrinterId = 7,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2019, 5, 30, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3714),
                            LocationId = 2,
                            Name = "Limpieza20",
                            PrinterId = 7,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2019, 5, 29, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3747),
                            LocationId = 2,
                            Name = "Calibracion21",
                            PrinterId = 7,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2019, 5, 16, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3777),
                            LocationId = 2,
                            Name = "Cambio Tinta22",
                            PrinterId = 8,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2019, 5, 14, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3808),
                            LocationId = 2,
                            Name = "Limpieza23",
                            PrinterId = 8,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2019, 5, 28, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3841),
                            LocationId = 2,
                            Name = "Calibracion24",
                            PrinterId = 8,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2019, 5, 15, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3873),
                            LocationId = 2,
                            Name = "Cambio Tinta25",
                            PrinterId = 9,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2019, 5, 22, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3905),
                            LocationId = 2,
                            Name = "Limpieza26",
                            PrinterId = 9,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2019, 5, 31, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3934),
                            LocationId = 2,
                            Name = "Calibracion27",
                            PrinterId = 9,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2019, 5, 21, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(3965),
                            LocationId = 2,
                            Name = "Cambio Tinta28",
                            PrinterId = 10,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2019, 5, 17, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4000),
                            LocationId = 2,
                            Name = "Limpieza29",
                            PrinterId = 10,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2019, 5, 17, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4030),
                            LocationId = 2,
                            Name = "Calibracion30",
                            PrinterId = 10,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTime(2019, 5, 16, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4069),
                            LocationId = 3,
                            Name = "Cambio Tinta31",
                            PrinterId = 11,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTime(2019, 5, 17, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4100),
                            LocationId = 3,
                            Name = "Limpieza32",
                            PrinterId = 11,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTime(2019, 5, 18, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4131),
                            LocationId = 3,
                            Name = "Calibracion33",
                            PrinterId = 11,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTime(2019, 5, 23, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4290),
                            LocationId = 3,
                            Name = "Cambio Tinta34",
                            PrinterId = 12,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTime(2019, 5, 21, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4324),
                            LocationId = 3,
                            Name = "Limpieza35",
                            PrinterId = 12,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTime(2019, 5, 18, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4358),
                            LocationId = 3,
                            Name = "Calibracion36",
                            PrinterId = 12,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTime(2019, 5, 28, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4393),
                            LocationId = 3,
                            Name = "Cambio Tinta37",
                            PrinterId = 13,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTime(2019, 6, 1, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4424),
                            LocationId = 3,
                            Name = "Limpieza38",
                            PrinterId = 13,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTime(2019, 5, 22, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4455),
                            LocationId = 3,
                            Name = "Calibracion39",
                            PrinterId = 13,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTime(2019, 5, 26, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4486),
                            LocationId = 3,
                            Name = "Cambio Tinta40",
                            PrinterId = 14,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTime(2019, 5, 26, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4515),
                            LocationId = 3,
                            Name = "Limpieza41",
                            PrinterId = 14,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTime(2019, 5, 31, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4545),
                            LocationId = 3,
                            Name = "Calibracion42",
                            PrinterId = 14,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTime(2019, 5, 31, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4576),
                            LocationId = 3,
                            Name = "Cambio Tinta43",
                            PrinterId = 15,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTime(2019, 5, 13, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4608),
                            LocationId = 3,
                            Name = "Limpieza44",
                            PrinterId = 15,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateTime(2019, 5, 28, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4638),
                            LocationId = 3,
                            Name = "Calibracion45",
                            PrinterId = 15,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 46,
                            Date = new DateTime(2019, 5, 26, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4667),
                            LocationId = 4,
                            Name = "Cambio Tinta46",
                            PrinterId = 16,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 47,
                            Date = new DateTime(2019, 5, 22, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4695),
                            LocationId = 4,
                            Name = "Limpieza47",
                            PrinterId = 16,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 48,
                            Date = new DateTime(2019, 5, 21, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4724),
                            LocationId = 4,
                            Name = "Calibracion48",
                            PrinterId = 16,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 49,
                            Date = new DateTime(2019, 5, 31, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4754),
                            LocationId = 4,
                            Name = "Cambio Tinta49",
                            PrinterId = 17,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 50,
                            Date = new DateTime(2019, 5, 14, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4785),
                            LocationId = 4,
                            Name = "Limpieza50",
                            PrinterId = 17,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 51,
                            Date = new DateTime(2019, 5, 31, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4814),
                            LocationId = 4,
                            Name = "Calibracion51",
                            PrinterId = 17,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 52,
                            Date = new DateTime(2019, 5, 22, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4938),
                            LocationId = 4,
                            Name = "Cambio Tinta52",
                            PrinterId = 18,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 53,
                            Date = new DateTime(2019, 6, 1, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(4975),
                            LocationId = 4,
                            Name = "Limpieza53",
                            PrinterId = 18,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 54,
                            Date = new DateTime(2019, 5, 31, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5008),
                            LocationId = 4,
                            Name = "Calibracion54",
                            PrinterId = 18,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 55,
                            Date = new DateTime(2019, 5, 27, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5039),
                            LocationId = 4,
                            Name = "Cambio Tinta55",
                            PrinterId = 19,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 56,
                            Date = new DateTime(2019, 5, 24, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5068),
                            LocationId = 4,
                            Name = "Limpieza56",
                            PrinterId = 19,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 57,
                            Date = new DateTime(2019, 5, 22, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5098),
                            LocationId = 4,
                            Name = "Calibracion57",
                            PrinterId = 19,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 58,
                            Date = new DateTime(2019, 5, 30, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5127),
                            LocationId = 4,
                            Name = "Cambio Tinta58",
                            PrinterId = 20,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 59,
                            Date = new DateTime(2019, 5, 25, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5155),
                            LocationId = 4,
                            Name = "Limpieza59",
                            PrinterId = 20,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 60,
                            Date = new DateTime(2019, 5, 15, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5185),
                            LocationId = 4,
                            Name = "Calibracion60",
                            PrinterId = 20,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 61,
                            Date = new DateTime(2019, 5, 25, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5212),
                            LocationId = 5,
                            Name = "Cambio Tinta61",
                            PrinterId = 21,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 62,
                            Date = new DateTime(2019, 5, 17, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5241),
                            LocationId = 5,
                            Name = "Limpieza62",
                            PrinterId = 21,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 63,
                            Date = new DateTime(2019, 5, 14, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5269),
                            LocationId = 5,
                            Name = "Calibracion63",
                            PrinterId = 21,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 64,
                            Date = new DateTime(2019, 5, 22, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5297),
                            LocationId = 5,
                            Name = "Cambio Tinta64",
                            PrinterId = 22,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 65,
                            Date = new DateTime(2019, 5, 27, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5326),
                            LocationId = 5,
                            Name = "Limpieza65",
                            PrinterId = 22,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 66,
                            Date = new DateTime(2019, 5, 16, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5357),
                            LocationId = 5,
                            Name = "Calibracion66",
                            PrinterId = 22,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 67,
                            Date = new DateTime(2019, 5, 20, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5386),
                            LocationId = 5,
                            Name = "Cambio Tinta67",
                            PrinterId = 23,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 68,
                            Date = new DateTime(2019, 5, 21, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5572),
                            LocationId = 5,
                            Name = "Limpieza68",
                            PrinterId = 23,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 69,
                            Date = new DateTime(2019, 5, 21, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5606),
                            LocationId = 5,
                            Name = "Calibracion69",
                            PrinterId = 23,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 70,
                            Date = new DateTime(2019, 5, 13, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5634),
                            LocationId = 5,
                            Name = "Cambio Tinta70",
                            PrinterId = 24,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 71,
                            Date = new DateTime(2019, 5, 30, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5664),
                            LocationId = 5,
                            Name = "Limpieza71",
                            PrinterId = 24,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 72,
                            Date = new DateTime(2019, 5, 27, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5692),
                            LocationId = 5,
                            Name = "Calibracion72",
                            PrinterId = 24,
                            Technician = "Dayneris"
                        },
                        new
                        {
                            Id = 73,
                            Date = new DateTime(2019, 5, 24, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5721),
                            LocationId = 5,
                            Name = "Cambio Tinta73",
                            PrinterId = 25,
                            Technician = "John Snow"
                        },
                        new
                        {
                            Id = 74,
                            Date = new DateTime(2019, 5, 15, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5750),
                            LocationId = 5,
                            Name = "Limpieza74",
                            PrinterId = 25,
                            Technician = "Cersei"
                        },
                        new
                        {
                            Id = 75,
                            Date = new DateTime(2019, 5, 31, 14, 39, 52, 597, DateTimeKind.Local).AddTicks(5780),
                            LocationId = 5,
                            Name = "Calibracion75",
                            PrinterId = 25,
                            Technician = "Dayneris"
                        });
                });

            modelBuilder.Entity("PrinterManagement.Models.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("LocationId");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("PersonInCharge");

                    b.Property<int>("PrinterType");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Printer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Epson",
                            LocationId = 1,
                            Model = "2010",
                            Name = "Printer1",
                            PersonInCharge = "Arya",
                            PrinterType = 3,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Sony",
                            LocationId = 1,
                            Model = "2011",
                            Name = "Printer2",
                            PersonInCharge = "Samsa",
                            PrinterType = 2,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "HP",
                            LocationId = 1,
                            Model = "2012",
                            Name = "Printer3",
                            PersonInCharge = "Ricon",
                            PrinterType = 0,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Dell",
                            LocationId = 1,
                            Model = "2013",
                            Name = "Printer4",
                            PersonInCharge = "Robb",
                            PrinterType = 1,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Ricon",
                            LocationId = 1,
                            Model = "2014",
                            Name = "Printer5",
                            PersonInCharge = "Bran",
                            PrinterType = 3,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Epson",
                            LocationId = 2,
                            Model = "2010",
                            Name = "Printer6",
                            PersonInCharge = "Arya",
                            PrinterType = 3,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Sony",
                            LocationId = 2,
                            Model = "2011",
                            Name = "Printer7",
                            PersonInCharge = "Samsa",
                            PrinterType = 2,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "HP",
                            LocationId = 2,
                            Model = "2012",
                            Name = "Printer8",
                            PersonInCharge = "Ricon",
                            PrinterType = 0,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Dell",
                            LocationId = 2,
                            Model = "2013",
                            Name = "Printer9",
                            PersonInCharge = "Robb",
                            PrinterType = 1,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Ricon",
                            LocationId = 2,
                            Model = "2014",
                            Name = "Printer10",
                            PersonInCharge = "Bran",
                            PrinterType = 3,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Epson",
                            LocationId = 3,
                            Model = "2010",
                            Name = "Printer11",
                            PersonInCharge = "Arya",
                            PrinterType = 3,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Sony",
                            LocationId = 3,
                            Model = "2011",
                            Name = "Printer12",
                            PersonInCharge = "Samsa",
                            PrinterType = 2,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "HP",
                            LocationId = 3,
                            Model = "2012",
                            Name = "Printer13",
                            PersonInCharge = "Ricon",
                            PrinterType = 0,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Dell",
                            LocationId = 3,
                            Model = "2013",
                            Name = "Printer14",
                            PersonInCharge = "Robb",
                            PrinterType = 1,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Ricon",
                            LocationId = 3,
                            Model = "2014",
                            Name = "Printer15",
                            PersonInCharge = "Bran",
                            PrinterType = 3,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Epson",
                            LocationId = 4,
                            Model = "2010",
                            Name = "Printer16",
                            PersonInCharge = "Arya",
                            PrinterType = 3,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Sony",
                            LocationId = 4,
                            Model = "2011",
                            Name = "Printer17",
                            PersonInCharge = "Samsa",
                            PrinterType = 2,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "HP",
                            LocationId = 4,
                            Model = "2012",
                            Name = "Printer18",
                            PersonInCharge = "Ricon",
                            PrinterType = 0,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Dell",
                            LocationId = 4,
                            Model = "2013",
                            Name = "Printer19",
                            PersonInCharge = "Robb",
                            PrinterType = 1,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Ricon",
                            LocationId = 4,
                            Model = "2014",
                            Name = "Printer20",
                            PersonInCharge = "Bran",
                            PrinterType = 3,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Epson",
                            LocationId = 5,
                            Model = "2010",
                            Name = "Printer21",
                            PersonInCharge = "Arya",
                            PrinterType = 3,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Sony",
                            LocationId = 5,
                            Model = "2011",
                            Name = "Printer22",
                            PersonInCharge = "Samsa",
                            PrinterType = 2,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 23,
                            Brand = "HP",
                            LocationId = 5,
                            Model = "2012",
                            Name = "Printer23",
                            PersonInCharge = "Ricon",
                            PrinterType = 0,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Dell",
                            LocationId = 5,
                            Model = "2013",
                            Name = "Printer24",
                            PersonInCharge = "Robb",
                            PrinterType = 1,
                            Serial = "01021"
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Ricon",
                            LocationId = 5,
                            Model = "2014",
                            Name = "Printer25",
                            PersonInCharge = "Bran",
                            PrinterType = 3,
                            Serial = "01021"
                        });
                });

            modelBuilder.Entity("PrinterManagement.Models.Maintenance", b =>
                {
                    b.HasOne("PrinterManagement.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrinterManagement.Models.Printer", "Printer")
                        .WithMany("Maintances")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PrinterManagement.Models.Printer", b =>
                {
                    b.HasOne("PrinterManagement.Models.Location", "Location")
                        .WithMany("Printers")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
